# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'venSalir.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(398, 141)
        self.btnBox = QtWidgets.QDialogButtonBox(Dialog)
        self.btnBox.setGeometry(QtCore.QRect(110, 100, 156, 23))
        self.btnBox.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.btnBox.setObjectName("btnBox")
        self.lblDeseasalir = QtWidgets.QLabel(Dialog)
        self.lblDeseasalir.setGeometry(QtCore.QRect(80, 20, 311, 71))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblDeseasalir.setFont(font)
        self.lblDeseasalir.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblDeseasalir.setObjectName("lblDeseasalir")
        self.lblImgsalir = QtWidgets.QLabel(Dialog)
        self.lblImgsalir.setGeometry(QtCore.QRect(70, 30, 41, 41))
        self.lblImgsalir.setText("")
        self.lblImgsalir.setPixmap(QtGui.QPixmap(":/icono/icono.jpg"))
        self.lblImgsalir.setObjectName("lblImgsalir")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblDeseasalir.setText(_translate("Dialog", "¿Estas seguro que deseas salir de la aplicacion?"))
import nuevo_rc
